update workflow

diff --git a/.github/workflows/build-csync2-rpmbuild-master.yml b/.github/workflows/build-csync2-rpmbuild-master.yml
--- a/.github/workflows/build-csync2-rpmbuild-master.yml
+++ b/.github/workflows/build-csync2-rpmbuild-master.yml
@@ -54,14 +54,29 @@ jobs:
           # Install the built RPM (non-debug version)
           echo
           yum localinstall -y /root/rpmbuild/RPMS/x86_64/csync2-2.*.x86_64.rpm
-          
+         
           # Check the installed RPM details
           echo
           yum info csync2
+
+          # Check permissions and ownership
+          echo
+          echo 'ls -l /etc/csync2'
+          ls -l /etc/csync2 || echo "/etc/csync2 does not exist"
+          echo
+          echo 'ls -l /usr/sbin/csync2'
+          ls -l /usr/sbin/csync2 || echo "csync2 binary not found in /usr/sbin"
           
           # Run the csync2 command to verify it works
           echo
-          csync2 --help
+          echo 'csync2 -v --help'
+          csync2 -v --help || true
+          echo
+          echo 'csync2 --help'
+          csync2 --help || true
+          echo
+          echo 'csync2 -v'
+          csync2 -v || true
         "
 
     - name: Debugging Show contents of /workspace/rpms
